from django.contrib.auth.models import User
from django.db import models


class lck_2021_spring_player(models.Model):
    nickname=models.CharField(max_length=15, primary_key=True)
    team=models.CharField(max_length=15)


class lck_2021(models.Model):
    champion=models.CharField(max_length=20)
    nickname=models.CharField(max_length=20)
    position=models.CharField(max_length=20)
    kill=models.IntegerField(3)
    death=models.IntegerField(3)
    assist=models.IntegerField(3)
    KDA=models.FloatField(5)
    CS=models.IntegerField(5)
    CS_in_Team_Jungle=models.IntegerField(5)
    CS_in_Enemy_Jungle=models.IntegerField(5)
    CSM=models.FloatField(5)
    Golds=models.IntegerField(5)
    GPM=models.FloatField(5)
    GOLDp=models.IntegerField(5)
    Vision_Scord=models.IntegerField(5)
    Wards_place=models.IntegerField(5)
    Wards_destroyed=models.IntegerField(5)
    control_ward_purchased=models.IntegerField(5)
    VSPM=models.FloatField(5)
    WPM=models.FloatField(5)
    VWPM=models.FloatField(5)
    WCPM=models.FloatField(5)
    VSp=models.IntegerField(5)
    Total_damage_to_champion=models.IntegerField(5)
    physical_damage=models.IntegerField(5)
    magic_damage=models.IntegerField(5)
    True_damage=models.IntegerField(5)
    DPM=models.IntegerField(5)
    DMGp=models.FloatField(5)
    KA_per_minute=models.FloatField(5)
    KPp=models.FloatField(5)
    solo_kill=models.IntegerField(5)
    Double_kills=models.IntegerField(5)
    Triple_kills=models.IntegerField(5)
    Quadra_kills=models.IntegerField(5)
    Penta_kills=models.IntegerField(5)
    GD15=models.IntegerField(5)
    CSD15=models.IntegerField(5)
    XPD15=models.IntegerField(5)
    LVLD15=models.IntegerField(5)
    Damage_dealt_to_turrets=models.IntegerField(5)
    Total_heal=models.IntegerField(5)
    Damage_self_mitigated=models.IntegerField(5)
    Time_ccing_others=models.IntegerField(5)
    Total_damage_taken=models.IntegerField(5)
    win=models.IntegerField(2)
