# Generated by Django 3.1.3 on 2021-03-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('kill', models.IntegerField(verbose_name=3)),
                ('death', models.IntegerField(verbose_name=3)),
                ('assist', models.IntegerField(verbose_name=3)),
                ('KDA', models.FloatField(verbose_name=5)),
                ('CS', models.IntegerField(verbose_name=5)),
                ('CS_in_Team_Jungle', models.IntegerField(verbose_name=5)),
                ('CS_in_Enemy_Jungle', models.IntegerField(verbose_name=5)),
                ('CSM', models.FloatField(verbose_name=5)),
                ('Golds', models.IntegerField(verbose_name=5)),
                ('GPM', models.FloatField(verbose_name=5)),
                ('GOLDp', models.IntegerField(verbose_name=5)),
                ('Vision_Scord', models.IntegerField(verbose_name=5)),
                ('Wards_place', models.IntegerField(verbose_name=5)),
                ('Wards_destroyed', models.IntegerField(verbose_name=5)),
                ('control_ward_purchased', models.IntegerField(verbose_name=5)),
                ('VSPM', models.FloatField(verbose_name=5)),
                ('WPM', models.FloatField(verbose_name=5)),
                ('VWPM', models.FloatField(verbose_name=5)),
                ('WCPM', models.FloatField(verbose_name=5)),
                ('VSp', models.IntegerField(verbose_name=5)),
                ('Total_damage_to_champion', models.IntegerField(verbose_name=5)),
                ('physical_damage', models.IntegerField(verbose_name=5)),
                ('magic_damage', models.IntegerField(verbose_name=5)),
                ('True_damage', models.IntegerField(verbose_name=5)),
                ('DPM', models.IntegerField(verbose_name=5)),
                ('DMGp', models.FloatField(verbose_name=5)),
                ('KA_per_minute', models.FloatField(verbose_name=5)),
                ('KPp', models.FloatField(verbose_name=5)),
                ('solo_kill', models.IntegerField(verbose_name=5)),
                ('Double_kills', models.IntegerField(verbose_name=5)),
                ('Triple_kills', models.IntegerField(verbose_name=5)),
                ('Quadra_kills', models.IntegerField(verbose_name=5)),
                ('Penta_kills', models.IntegerField(verbose_name=5)),
                ('GD15', models.IntegerField(verbose_name=5)),
                ('CSD15', models.IntegerField(verbose_name=5)),
                ('XPD15', models.IntegerField(verbose_name=5)),
                ('LVLD15', models.IntegerField(verbose_name=5)),
                ('Damage_dealt_to_turrets', models.IntegerField(verbose_name=5)),
                ('Total_heal', models.IntegerField(verbose_name=5)),
                ('Damage_self_mitigated', models.IntegerField(verbose_name=5)),
                ('Time_ccing_others', models.IntegerField(verbose_name=5)),
                ('Total_damage_taken', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
