# Generated by Django 3.1.3 on 2021-03-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0006_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('league', models.CharField(max_length=20)),
                ('short', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=20)),
            ],
        ),
    ]
