# Generated by Django 3.1.3 on 2021-03-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0007_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='report',
            new_name='lck_2021',
        ),
        migrations.DeleteModel(
            name='team',
        ),
    ]
