# Generated by Django 3.1.3 on 2021-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0008_auto_20210307_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='lck_2021_spring_player',
            fields=[
                ('nickname', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='lck_2021',
            name='win',
            field=models.IntegerField(default=1, verbose_name=2),
            preserve_default=False,
        ),
    ]
